// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:c0cf2391-aad2-4ccf-81e5-bcbcc0f995b8',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsstarter-hosting-mobilehub-441855764',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1oxiaiwaallt.cloudfront.net',
    'aws_mobile_analytics_app_id': '100594e383f441b282b83b73bdb2818b',
    'aws_project_id': 'd364ddc3-d738-4a48-917e-5de14056e6b5',
    'aws_project_name': 'awsStarter',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'awsstarter-mobilehub-441855764',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'awsstarter-userfiles-mobilehub-441855764',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_07iFnZ6FU',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '3p3qf13a5m5v4pncbt62drveo4',
    'aws_user_settings': 'enable',
}

export default awsmobile;
